/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hoogenbj.wordle.lookalike;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXMLLoader;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;
import javafx.stage.WindowEvent;

public class App extends Application {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        FXMLLoader loader = new FXMLLoader();
        loader.setLocation(this.getClass().getResource("/WordleLookalike.fxml"));
        Parent root = loader.load();
        Scene scene = new Scene(root);
        primaryStage.setScene(scene);
        primaryStage.setTitle("Wordle Lookalike");
        primaryStage.show();
        scene.getWindow().setOnCloseRequest((WindowEvent t) -> {
            if (t.getEventType().equals(WindowEvent.WINDOW_CLOSE_REQUEST)) {
                Platform.exit();
            }
        });
    }
}
